version: '3.8'

services:
  mistralai:
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    command: --host 0.0.0.0 --model mistralai/Mistral-7B-Instruct-v0.2
    environment:
      HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    env_file:
      - token.env

